apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
      - name: capstone-app
        image: IMAGE_PLACEHOLDER:TAG_PLACEHOLDER  # Placeholders for image and tag
        imagePullPolicy: Always
        ports:
        - containerPort: 8080  # Correct port for the application
